name: Build Jekyll Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/s110b/jekyll:latest

    steps:
    - uses: actions/checkout@v4
    


    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2' # Jekyll 目前与 Ruby 2.7 兼容

    - name: Build Jekyll site
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build
