name: Build Jekyll Site1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/s110b/jekyll:latest

    steps:
    - uses: actions/checkout@v4
    




    - name: Build Jekyll site
      run: |
        gem install bundler
        bundle update --bundler
        bundle install
        bundle exec jekyll build
