name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Output directory structure after checkout
      run: |
        sudo apt-get install -y tree
        tree ${{ github.workspace }}

# 必须等待jekyll编译完成，服务启动成功，才能拷贝文件。否则拷贝的是个空目录。
    - name: Start server, wait, copy directory, get logs
      run: |
        echo "Starting Jekyll server..."
        docker-compose up -d
        echo "Waiting for Jekyll server to start..."
        docker logs -f photo-stream | while read line
        do
          echo $line
          if [[ $line == *"running"* ]]; then
          echo "Jekyll server has started."
          echo "Copying _site directory and outputting its structure..."
          docker cp $(docker ps -lq):/photo-stream/_site .
          tree _site
          pkill -P $$ docker
          break
        fi
        done
        echo "Getting Docker logs..."
        docker exec $(docker ps -lq) ls -l /photo-stream/_site


    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: _site

    - name: Publish to cloudflare
      uses: cloudflare/pages-action@1
      with:
        apiToken: sgs661R3UiFDmpt3odP5kEO8HkTl4Io9NAJmjRyX
        accountId: 80d039f72d9b6bbdb8076a69c9a9e164
        projectName: jd # e.g. 'my-project'
        directory: '.' # e.g. 'dist'
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}



#    - name: Copy _site directory from Docker container to local
#      run: |
#        docker cp $(docker ps -lq):/_site ${{ github.workspace }}/_site
#
#    - name: Output directory structure after running image
#      run: tree ${{ github.workspace }}/_site
