name: Build Docker Image and Push Files to GitHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        tags: test:latest

    - name: Run Docker image and mount build directory
      run: |
        docker run -v ${{ github.workspace }}/_site:/_site test:latest

    - name: Install tree and output directory structure
      run: |
        sudo apt-get install -y tree
        tree ${{ github.workspace }}/_site
