name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Output directory structure after checkout
      run: |
        sudo apt-get install -y tree
        tree ${{ github.workspace }}

    - name: Build and run with Docker Compose
      run: |
        docker-compose up -d

    - name: Get Docker logs
      run: docker exec $(docker ps -lq) ls -l /photo-stream/_site

    - name: Copy _site directory and output its structure
      run: |
        docker cp $(docker ps -lq):/photo-stream/_site .
        tree _site

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: _site



#    - name: Copy _site directory from Docker container to local
#      run: |
#        docker cp $(docker ps -lq):/_site ${{ github.workspace }}/_site
#
#    - name: Output directory structure after running image
#      run: tree ${{ github.workspace }}/_site
