name: Build Docker Image and Push Files to GitHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Output directory structure after checkout
      run: |
        sudo apt-get install -y tree
        tree ${{ github.workspace }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        tags: test:latest

    - name: Output directory structure after building image
      run: tree ${{ github.workspace }}

    - name: Run Docker image and mount build directory
      run: |
        docker run -d test:latest
        docker exec $(docker ps -lq) tree /



    - name: Copy _site directory from Docker container to local
      run: |
        docker cp $(docker ps -lq):/_site ${{ github.workspace }}/_site

    - name: Output directory structure after running image
      run: tree ${{ github.workspace }}/_site
