name: Build Docker Image and Push Files to GitHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Output directory structure after checkout
      run: |
        sudo apt-get install -y tree
        tree ${{ github.workspace }}

    - name: Build Docker image
      run: docker build -t test:latest .

    - name: Run Docker container
      id: run
      run: echo "::set-output name=container_id::$(docker run -d test:latest)"



    - name: Run Docker image and mount build directory
      run: |
        docker logs ${{ steps.run.outputs.container_id }}
        docker exec $(docker ps -lq) tree /photo-stream



#    - name: Copy _site directory from Docker container to local
#      run: |
#        docker cp $(docker ps -lq):/_site ${{ github.workspace }}/_site
#
#    - name: Output directory structure after running image
#      run: tree ${{ github.workspace }}/_site
