name: Build Docker Image and Push Files to GitHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Output directory structure after checkout
      run: |
        sudo apt-get install -y tree
        tree ${{ github.workspace }}

    - name: Build and run with Docker Compose
      run: |
        docker-compose up -d

    - name: Get Docker logs
      docker exec $(docker ps -lq) ls -l /photo-stream



#    - name: Copy _site directory from Docker container to local
#      run: |
#        docker cp $(docker ps -lq):/_site ${{ github.workspace }}/_site
#
#    - name: Output directory structure after running image
#      run: tree ${{ github.workspace }}/_site
